draw_config:
  n_columns: 1
  draw_key_sides: true
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 28.0
  combo_h: 26.0
  key_rx: 6.0
  key_ry: 6.0
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 40.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  svg_extra_style: |
    /* For default sytles, see https://github.com/caksoylar/keymap-drawer/blob/main/keymap_drawer/config.py#L85 */

    svg.keymap {
      font-family: Ubuntu Mono, Inconsolata, Consolas, Liberation Mono, Menlo, monospace;
      font-size: 12px;
      font-weight: bold;
      text-rendering: optimizeLegibility;
    }

    /* Color accent for held keys */
    rect.held, rect.combo.held {
        fill: #D7EDF5;
    }

    /* Technique borrowed and extended from https://github.com/englmaxi/zmk-config/blob/master/keymap-drawer/config.yaml */
    .sym_sub_text.tap {
      translate: -5px 2px;
      font-size: 20px;
    }
    .sym_sub_text.shifted {
      translate: 10px 13px;
      font-size: 10px;
      opacity: 1.0;
    }
    .combo.sym_sub_text.tap {
      translate: -1px 1px;
    }
    .combo.sym_sub_text.shifted {
      translate: 7px 5px;
      font-size: 10px;
      opacity: 1.0;
    }

    /* Toggle */
    .toggle.shifted {
      translate: -10px 12px;
    }

    .toggle.hold {
      translate: 13px -23px;
    }

    /* Variant for tap-dances */
    .tap_dance.tap {
      translate: -7px 0px;
      font-size: 12px;
    }
    .tap_dance.shifted {
      translate: 7px 17px;
      font-size: 12px;
      opacity: 1.0;
    }

    /* Variant for symbol next to symbol */
    .sym_by_sym.tap {
      translate: -6px 0px;
    }
    .sym_by_sym.shifted {
      translate: 10px 12px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.tap {
      translate: -35px 0px;
    }
    .combo.sym_by_sym.shifted {
      translate: 35px 20px;
      opacity: 1.0;
    }

    .combo.sym_by_sym.hold {
      visibility: hidden;
    }

    /* hide hold box for combo sym_by_sym */
    .combo.sym_by_sym.hold > path[stroke="none"][fill="none"] {
      visibility: hidden;
    }

  shrink_wide_legends: 6
  glyph_tap_size: 18
  glyph_hold_size: 15
  glyph_shifted_size: 15
  glyphs: {}
  glyph_urls:
    tabler: https://unpkg.com/@tabler/icons/icons/outline/{}.svg
    tablerf: https://unpkg.com/@tabler/icons/icons/filled/{}.svg
    mdi: https://raw.githubusercontent.com/Templarian/MaterialDesign-SVG/master/svg/{}.svg
    mdil: https://raw.githubusercontent.com/Pictogrammers/MaterialDesignLight/master/svg/{}.svg
    material: https://fonts.gstatic.com/s/i/short-term/release/materialsymbolsoutlined/{}/default/48px.svg
  use_local_cache: true

parse_config:
  mark_alternate_layer_activators: true
  sticky_label: $$mdi:gesture-tap-hold$$
  toggle_label: $$mdi:toggle-switch$$
  trans_legend:
    tap: $$mdi:transfer$$
    type: trans

  raw_binding_map:

    # LAYERS
    
    ## layer-Tap
    "&ltq 1 BACKSPACE":
      tap:  $$mdi:backspace$$
      hold: '$$mdi:navigation-variant$$'
    "&ltq 3 TAB":
      tap: $$mdi:keyboard-tab$$
      hold: $$mdi:numeric$$
    "&ltq 2 SPACE":
      tap: $$mdi:keyboard-space$$
      hold: $$mdi:symbol$$
    "&ltq 3 ENTER":
      tap: $$mdi:keyboard-return$$
      hold: $$mdi:numeric$$
    "&ltq 1 DELETE":
      tap: $$mdi:backspace-reverse-outline$$
      hold: $$mdi:navigation-variant$$

    ## Layer Toggle
    "&tog 1":
      tap: $$mdi:toggle-switch$$
      shifted: '1'
    "&tog 2":
      tap: $$mdi:toggle-switch$$
      shifted: '2'
    "&tog 3":
      tap: $$mdi:toggle-switch$$
      shifted: '3'

    #-----------------------------------------------
    
    # MODIFIERS

    # Custom mods
    "&rpi LCTRL SPACE": 
      tap: $$mdi:keyboard-space$$
      hold: "CTRL"
    "&rpi RCTRL SPACE":
      tap: $$mdi:keyboard-space$$
      hold: "CTRL"
    "&tesc":
      tap: "ESC"
      shifted: "~"

    ## Home Row Mods
    "&hm LEFT_GUI A":
      tap: 'A'
      shifted: "WIN"
    "&hm LEFT_ALT S":
      tap: 'S'
      shifted: "ALT"
    "&hm LEFT_CONTROL D":
      tap: 'D'
      shifted: "WIN"
    "&hm LEFT_SHIFT F":
      tap: 'F'
      shifted: $$material:shift$$
    "&hm RIGHT_SHIFT J":
      tap: 'J'
      shifted: $$material:shift$$
    "&hm RIGHT_CONTROL K":
      tap: 'K'
      shifted: "WIN"
    "&hm RIGHT_ALT L":
      tap: 'L'
      shifted: "ALT"

    # self behaviors
    "&hm LG(LS(V)) P":
      tap: 'P'
      shifted: $$mdi:content-copy$$
    
    # Other modifiers
    "&caps_word": $$mdi:alpha-w-box$$
    "&kt RSHIFT":
      tap: $$material:shift$$
      hold: $$mdi:toggle-switch$$

    #-----------------------------------------------

    # MOUSE

    ## Mouse Scroll
    "&msc SCRL_UP":
      tap: $$mdi:pan-up$$
      hold: ''
      shifted: ''
    "&msc SCRL_DOWN":
      tap: $$mdi:pan-down$$
      hold: ''
      shifted: ''
    "&msc SCRL_LEFT":
      tap: $$mdi:pan-left$$
      hold: ''
      shifted: ''
    "&msc SCRL_RIGHT":
      tap: $$mdi:pan-right$$
      hold: ''
      shifted: ''
    
    ## Mouse Move
    "&mmv MOVE_LEFT":
      shifted: $$mdi:menu-left$$
      hold: ''
      tap: $$mdi:mouse$$
    "&mmv MOVE_RIGHT":
      shifted: $$mdi:menu-right$$
      hold: ''
      tap: $$mdi:mouse$$
    "&mmv MOVE_UP":
      shifted: $$mdi:menu-up$$
      hold: ''
      tap: $$mdi:mouse$$
    "&mmv MOVE_DOWN":
      shifted: $$mdi:menu-down$$
      hold: ''
      tap: $$mdi:mouse$$
    
    ## Mouse Click
    "&mkp LCLK":
      tap: $$mdi:mouse-left-click$$
    "&mkp RCLK":
      tap: $$mdi:mouse-right-click$$
    "&mkp MCLK":
      tap: $$mdi:mouse-scroll-wheel$$

  #-----------------------------------------------


    # Empty
    "&none":
      tap: $$mdi:minus-circle-outline$$
      type: none

    # Whitespace
    "&bkspc_del":
      type: backspace
      tap: $$mdi:backspace$$
      shifted: $$mdi:backspace-reverse-outline$$

  #-----------------------------------------------

    # BLUETOOTH

    ## BT Select connection
    "&bt BT_SEL 0":
      shifted: $$mdi:bluetooth-connect$$
      tap: 1
    "&bt BT_SEL 1":
      shifted: $$mdi:bluetooth-connect$$
      tap: 2
    "&bt BT_SEL 2":
      shifted: $$mdi:bluetooth-connect$$
      tap: 3
    "&bt BT_SEL 3":
      shifted: $$mdi:bluetooth-connect$$
      tap: 4
    "&bt BT_SEL 4":
      shifted: $$mdi:bluetooth-connect$$
      tap: 5
    
    ## BT Select
    "&bt BT_NXT":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: $$mdi:arrow-down-bold$$
    "&bt BT_PRV":
      shifted: $$mdi:bluetooth-connect$$
      tap: ""
      hold: $$mdi:arrow-up-bold$$

    ## Output
    "&out OUT_TOG":
      shifted: $$mdi:usb$$
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
    "&out OUT_USB":
      shifted: "OUT"
      tap: $$mdi:usb$$
    "&out OUT_BLE": 
      shifted: "OUT"
      tap: $$mdi:bluetooth-connect$$

  #-----------------------------------------------  
    
    # SYSTEM

    "&sys_reset":
      type: bootloader
      tap: $$mdi:backup-restore$$
    "&bootloader":
      tap: $$mdi:progress-download$$

    #-----------------------------------------------

    # MACROS

    "&M_VShtml": $$material:HTML$$
    "&M_VSlang":
      tap: $$material:Code$$
      shifted: $$material:Language$$
      hold: "VS Code"
    "&M_zero": "00"


  #-------------------------------------------------
  #-------------------------------------------------

  # ZMK
  zmk_keycode_map:

    # STANDARD KEYS

    ## Symbols
    EXCLAMATION: "!"
    EXCL: "!"
    AT_SIGN: "@"
    AT: "@"
    HASH: "#"
    POUND: "#"
    DOLLAR: $
    DLLR: $
    PERCENT: "%"
    PRCNT: "%"
    CARET: ^
    AMPERSAND: "&"
    AMPS: "&"
    ASTERISK: "*"
    ASTRK: "*"
    STAR: "*"
    LEFT_PARENTHESIS: (
    LPAR: (
    RIGHT_PARENTHESIS: )
    RPAR: )
    EQUAL:
      tap: "="
      shifted: "+"
    PLUS: +
    MINUS:
      tap: "-"
      shifted: "_"
    UNDERSCORE: _
    UNDER: _
    SLASH:
      tap: "/"
      shifted: "?"
    FSLH:
      tap: "/"
      shifted: "?"
    QUESTION: "?"
    QMARK: "?"
    BACKSLASH:
      tap: '\'
      shifted: "|"
    BSLH:
      tap: '\'
      shifted: "|"
    PIPE: "|"
    NON_US_BACKSLASH: \
    PIPE2: "|"
    NON_US_BSLH: "|"
    SEMICOLON:
      tap: ";"
      shifted: ":"
    SEMI:
      tap: ";"
      shifted: ":"
    COLON: ":"
    SINGLE_QUOTE:
      tap: "'"
      shifted: '"'
    SQT:
      tap: "'"
      shifted: '"'
    APOSTROPHE: 
      tap: "'"
      shifted: '"'
    APOS:
      tap: "'"
      shifted: '"'
    DOUBLE_QUOTES: '"'
    DQT: '"'
    LESS_THAN: <
    LT: <
    PERIOD: '.'
    DOT:
      tap: "."
      shifted: ">"
    COMMA:
      tap: ","
      shifted: "<"
    GREATER_THAN: ">"
    GT: ">"
    LEFT_BRACKET:
      tap: "["
      shifted: "{"
    LBKT:
      tap: "["
      shifted: "{"
    LEFT_BRACE: "{"
    LBRC: "{"
    RIGHT_BRACKET:
      tap: "]"
      shifted: "}"
    RBKT:
      tap: "]"
      shifted: "}"
    RIGHT_BRACE: "}"
    RBRC: "}"
    GRAVE:
      tap: "`"
      shifted: "~"
    TILDE: "~"
    NON_US_HASH: "#"
    NUHS: "#"
    TILDE2: "~"

    ## Numbers
    N1:
      tap: 1
      shifted: "!"
    N2:
      tap: 2
      shifted: "@"
    N3:
      tap: 3
      shifted: "#"
    N4:
      tap: 4
      shifted: "$"
    N5:
      tap: 5
      shifted: "%"
    N6:
      tap: 6
      shifted: "^"
    N7:
      tap: 7
      shifted: "&"
    N8:
      tap: 8
      shifted: "*"
    N9:
      tap: 9
      shifted: "("
    N0:
      tap: 0
      shifted: ")"

    ## Numpad
    KP_SLASH: "/"
    KP_ASTERISK: "*"
    KP_PLUS: "+"
    KP_DOT: "."
    KP_N0: "0"
    KP_N1: "1"
    KP_N2: "2"
    KP_N3: "3"
    KP_N4: "4"
    KP_N5: "5"
    KP_N6: "6"
    KP_N7: "7"
    KP_N8: "8"
    KP_N9: "9"

    ## Modifiers
    LCTRL: "CTRL"
    LEFT_CONTROL: "CTRL"
    LALT: "ALT"
    LEFT_ALT: "ALT"
    LSHIFT: $$material:shift$$
    LEFT_SHIFT: $$material:shift$$
    LSHFT: $$material:shift$$
    LCMD: $$mdi:apple-keyboard-command$$
    LG: $$mdi:microsoft$$
    LEFT_GUI: $$mdi:microsoft$$
    LGUI: $$mdi:microsoft$$
    LEFT_COMMAND: $$mdi:apple-keyboard-command$$
    RCTRL: "CTRL"
    RIGHT_CONTROL: "CTRL"
    RALT: "ALT"
    RIGHT_ALT: "ALT"
    RSHIFT: $$material:shift$$
    RIGHT_SHIFT: $$material:shift$$
    RSHFT: $$material:shift$$
    RCMD: $$mdi:apple-keyboard-command$$
    RG: $$mdi:microsoft$$
    RGUI: $$mdi:microsoft$$
    RIGHT_GUI: $$mdi:microsoft$$
    RIGHT_COMMAND: $$mdi:apple-keyboard-command$$
    ### "Meh" key
    LS(LC(LALT)): $$mdi:star-three-points$$

    ## Navigation
    PSCRN: $$mdi:printer-outline$$
    PAGE_UP:
      tap: 'PgUp'
      shifted: ''
    PAGE_DOWN:
      tap: 'PgDn'
      shifted: ''
    INSERT:
       tap: 'Ins'
       shifted: ''
    K_APP: $$mdi:menu$$
    K_CALC: $$mdi:calculator$$
    
    ## Arrows
    UP: $$mdi:arrow-up-bold$$
    UP_ARROW: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    DOWN_ARROW: $$mdi:arrow-down-bold$$
    LEFT_ARROW: $$mdi:arrow-left-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$
    RIGHT_ARROW: $$mdi:arrow-right-bold$$

    ## Whitespace
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    ESCAPE: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    ## Locks
    CAPSLOCK: $$material:shift_lock$$
    CAPS: $$material:shift_lock$$

    #-----------------------------------------------

    # EXTRAS

    ## Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$
    C_VOLUME_UP: $$mdi:volume-high$$
    C_VOLUME_DOWN: $$mdi:volume-low$$

    ## Media
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$

    ## Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$
    BT_CLR_ALL: 
      shifted: "ALL"
      tap: $$mdi:bluetooth-off$$

    ## Settings
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRIGHTNESS_INC: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$
    C_BRI_DEC: $$mdi:brightness-7$$
    C_BRIGHTNESS_DEC: $$mdi:brightness-7$$

    ## System
    C_POWER: $$mdi:power-standby$$
    C_AL_LOCK: $$mdi:lock$$
    K_CANCEL: $$mdi:close-box$$
    K_FIND: $$mdi:apple-finder$$

    ## Shortcuts
    LC(S): $$mdi:content-save$$
    LC(LS(S)): $$mdi:content-save-edit$$
    LC(P): $$mdi:printer$$
    LC(O): $$mdi:folder-open$$
    LC(LA(DEL)): "CTL ALT DEL"
    LC(F5): $$mdi:web-refresh$$
    LC(F2):
      tap: $$material:quick_reference_all_24$$
      hold: "VS Code"
    LA(LS(F)):
      tap: $$mdi:language-html5$$
      shifted: "FORMAT"
      hold: "VS Code"
    LC(LS(V)):
      tap: $$mdi:content-paste$$
      shifted: "TEXT"
    LC(LA(DOWN)):
      tap: $$mdi:cursor-text$$
      shifted: $$mdi:arrow-expand-down$$
    LS(LEFT):
      tap: $$mdi:format-color-highlight$$
      shifted: $$mdi:arrow-left-thin$$
    LS(DOWN):
      tap: $$mdi:format-color-highlight$$
      shifted: $$mdi:arrow-down-thin$$
    LS(RIGHT):
      tap: $$mdi:format-color-highlight$$
      shifted: $$mdi:arrow-right-thin$$
    LC(LEFT):
      tap: $$material:match-word$$
      shifted: $$mdi:arrow-left-thin$$
    LC(DOWN):
      tap: $$material:match-word$$
      shifted: $$mdi:arrow-down-thin$$
    LC(RIGHT):
      tap: $$material:match-word$$
      shifted: $$mdi:arrow-right-thin$$
    LC(UP):
      tap: $$material:match-word$$
      shifted: $$mdi:arrow-right-thin$$
    
    ## Command + 
    LG(A):
      tap: 'A'
      hold: $$mdi:apple-keyboard-command$$
    LG(S):
      tap: 'S'
      hold: $$mdi:apple-keyboard-command$$
    LG(D):
      tap: 'D'
      hold: $$mdi:apple-keyboard-command$$
    LG(F):
      tap: 'F'
      hold: $$mdi:apple-keyboard-command$$
    LG(Z):
      tap: 'Z'
      hold: $$mdi:apple-keyboard-command$$
    LG(X):
      tap: 'X'
      hold: $$mdi:apple-keyboard-command$$
    LG(C):
      tap: 'C'
      hold: $$mdi:apple-keyboard-command$$
    LG(V):
      tap: 'V'
      hold: $$mdi:apple-keyboard-command$$

    ## Zoom
    RG(RS(A)):
      tap: $$mdi:microphone$$
      hold: zoom
    RG(RS(V)):
      tap: $$mdi:video$$
      hold: zoom
 
  zmk_combos:
    combo_to_2:
      align: top
    combo_to_3:
      align: top
    combo_bt_clear:
      align: top
      offset: 0.03
    combo_mute:
      align: top
      offset: 0.15
    combo_minus:
      key:
        shifted: "_"
        hold: "-"
    combo_equal:
      key:
        shifted: "+"
        hold: "="
    combo_backslash:
      key:
        shifted: "|"
        hold: \
    combo_lbkt:
      key:
        shifted: "{"
        hold: "["
    combo_rbkt:
      key:
        shifted: "}"
        hold: "]"
    combo_semicolon:
      key:
        shifted: ":"
        hold: ";"